git:
  commitMessage: 'Release v${version}'
  requireUpstream: false
  tag: true
  push: true

npm:
  publish: true

hooks:
  before:init:
    - git checkout main
    - git pull --rebase
    - npm install
    - make validate tests
